// let bestsellers = [
//   {
//     name: "phone",
//     type: "android",
//     price: 14401,
//     old: "16990$",
//     discount:17
//   },

//   {
//     name: "chgiem",
//     type: "zanaveska",
//     price: 650,
//     old: "6500$",
//     discount:45
//   },
//   {
//     name: "erexa",
//     type: "pink",
//     price: 840,
//     old: "1200$",
//     discount:15
//   },
//   {
//     name: "phone",
//     type: "andriod",
//     price: 120,
//     old: "16990$",
//     discount:null
//   },
//   {
//     name: "headphones",
//     type: "gamer",
//     price: 750,
//     old: "3000$",
//     discount:60
//   },
//   {
//     name: "miBan",
//     type: "chgidem",
//     price: 325,
//     old: "1300$",
//     discount:null
//   },
//   {
//     name:'axchkahamar',
//     type:'makeup',
//     price:169,
//     old:'999$',
//     discount:99
//   }
// ];
// for (let index = 0; index < bestsellers.length; index++) {
//     const element = bestsellers[index];
//     if (element.discount ) {
// if (element.price < 250) {
//     console.log(element.name, '==> ', element.price);
    
// }
//     }
// }
