let OurMenu = [
  {
    name: "Bread Basket",
    ingredients: "Assortment of fresh baked fruit breads and muffins 5.50",
  },
  {
    name: "Honey Almond Granola with Fruits",
    ingredients:
      "Natural cereal of honey toasted oats, raisins, almonds and dates 7.00",
  },
  {
    name: "Belgian Waffle",
    ingredients: "Vanilla flavored batter with malted flour 7.50",
  },
  {
    name: "Scrambled eggs",
    ingredients:
      "Scrambled eggs, roasted red pepper and garlic, with green onions 7.50 ",
  },
  {
    name:'Blueberry Pancakes',
    ingredients:'With syrup, butter and lots of berries 8.50'
  }
];

function changeText(text) {
  return text.split('').join(' ')
}
